title: HashMaps, HashSets, Collections, and SQL
description: "Lesson for CSA 12/14/2023 - 12/14/2023 (but slightly later)"
owner_name: Tirth Thakkar 
github_username: Tirth-Thakkar
github_repo: "LessonGroup"
baseurl: "/LessonGroup"
remote_theme: jekyll/minima
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/Tirth-Thakkar"}
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/hacker@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme
future: true
